import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layouts/Footer/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative overflow-x-hidden `}>
        <main>{children}</main>
        <footer className="mt-24 relative h-[358px] bg-[#161A4F]">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
